from .header import show_header
from .image_upload import image_upload_section
from .results_display import show_detection_results
from .batch_processing import batch_processing_section,show_batch_results
from .recycling_guide import show_recycling_guide